### ISSUE TITLE
docker image arm64v8 (arm64, aarch64) does not work

### ISSUE THREAD

**Issue by zarusz** [docker-library/rabbitmq#206]
The image `arm64v8/rabbitmq:3` does not seem to work on an `aarch64` platform.

Running docker image `arm64v8/rabbitmq:3`:
```
docker run -d --hostname rock64 --name some-rabbit -v /storage/rabbitmq:/var/lib/rabbitmq arm64v8/rabbitmq:3
```
Gives an error response:
```
docker: Error response from daemon: containerd: container not started.
```
Going into container logs I get:
```
Rock64:~ # docker logs some-rabbit
runtime: no module data for 0x20000004d5f78
fatal error: no module data
runtime stack:
runtime.throw(0x7c61c5, 0xe)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/panic.go:566 +0x80
runtime.pcvalue(0x880e90, 0x60882, 0x4d60f0, 0x7fd0d14e18, 0x7dea01, 0x8ead18)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/symtab.go:421 +0x1cc
runtime.funcspdelta(0x880e90, 0x4d60f0, 0x7fd0d14e18, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/symtab.go:511 +0x4c
runtime.gentraceback(0x429a98, 0x44200d4370, 0x426a98, 0x44200001a0, 0x0, 0x0, 0x7fffffff, 0x7f86d8, 0x7fd0d150b8, 0x0, ...)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/traceback.go:264 +0x970
runtime.copystack(0x44200001a0, 0x4000, 0x1)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/stack.go:902 +0x358
runtime.newstack()
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/stack.go:1070 +0xa80
runtime.morestack()
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/asm_arm64.s:300 +0x5c
goroutine 1 [copystack, locked to thread]:
runtime.heapBitsSetType(0x44200c0130, 0x10, 0x10, 0x757ee0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/mbitmap.go:867 fp=0x44200d4370 sp=0x44200d4370
runtime.mallocgc(0x10, 0x757ee0, 0x1, 0x426a98)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/malloc.go:690 +0x820 fp=0x44200d4440 sp=0x44200d4370
runtime.makeslice(0x757ee0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/slice.go:57 +0xb8 fp=0x44200d4490 sp=0x44200d4440
strings.genSplit(0x7d4a88, 0x2, 0x7c261a, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/strings/strings.go:249 +0xf0 fp=0x44200d4520 sp=0x44200d4490
strings.Split(0x7d4a88, 0x2, 0x7c261a, 0x1, 0x0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/strings/strings.go:287 +0x54 fp=0x44200d4570 sp=0x44200d4520
text/template/parse.(*Tree).newVariable(0x442000c2a0, 0x8d, 0x7d4a88, 0x2, 0x7d4a43)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/node.go:330 +0x40 fp=0x44200d45d0 sp=0x44200d4570
text/template/parse.(*Tree).useVar(0x442000c2a0, 0x8d, 0x7d4a88, 0x2, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:725 +0x40 fp=0x44200d46b0 sp=0x44200d45d0
text/template/parse.(*Tree).term(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:676 +0x954 fp=0x44200d4900 sp=0x44200d46b0
text/template/parse.(*Tree).operand(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:625 +0x2c fp=0x44200d4be0 sp=0x44200d4900
text/template/parse.(*Tree).command(0x442000c2a0, 0x13)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:596 +0xd4 fp=0x44200d4d70 sp=0x44200d4be0
text/template/parse.(*Tree).pipeline(0x442000c2a0, 0x7c387c, 0x7, 0x44200c6140)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:430 +0x5e0 fp=0x44200d5080 sp=0x44200d4d70
text/template/parse.(*Tree).action(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:381 +0x180 fp=0x44200d51b0 sp=0x44200d5080
text/template/parse.(*Tree).textOrAction(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:350 +0x5c fp=0x44200d5250 sp=0x44200d51b0
text/template/parse.(*Tree).itemList(0x442000c2a0, 0x44200c2360, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:332 +0xdc fp=0x44200d52f0 sp=0x44200d5250
text/template/parse.(*Tree).parseControl(0x442000c2a0, 0x4420054900, 0x7c3060, 0x5, 0x0, 0x6, 0x44200c60f0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:457 +0x108 fp=0x44200d54c0 sp=0x44200d52f0
text/template/parse.(*Tree).rangeControl(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:499 +0x4c fp=0x44200d5550 sp=0x44200d54c0
text/template/parse.(*Tree).action(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:373 +0x3d8 fp=0x44200d5680 sp=0x44200d5550
text/template/parse.(*Tree).textOrAction(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:350 +0x5c fp=0x44200d5720 sp=0x44200d5680
text/template/parse.(*Tree).parse(0x442000c2a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:295 +0x534 fp=0x44200d5a80 sp=0x44200d5720
text/template/parse.(*Tree).Parse(0x442000c2a0, 0x7d49fb, 0xf0, 0x0, 0x0, 0x0, 0x0, 0x4420012ff0, 0x442001ede0, 0x2, ...)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:234 +0x25c fp=0x44200d5b10 sp=0x44200d5a80
text/template/parse.Parse(0x7c2f8e, 0x5, 0x7d49fb, 0xf0, 0x0, 0x0, 0x0, 0x0, 0x442001ede0, 0x2, ...)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/parse.go:55 +0xf4 fp=0x44200d5ba0 sp=0x44200d5b10
text/template.(*Template).Parse(0x44200548c0, 0x7d49fb, 0xf0, 0x4a04a0, 0x0, 0x0)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/template.go:190 +0x2bc fp=0x44200d5ce0 sp=0x44200d5ba0
invalid spdelta  0x20000004d5f78 0x4d60f0 0x60882 -1
()
        ?:0 fp=0x44200d5cdf sp=0x44200d5ce0
main.init()
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/runc-9df8b30/utils_linux.go:308 +0x7c fp=0x44200d5eaf sp=0x44200d5cdf
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/runtime/asm_arm64.s:983 +0x4
goroutine 5 [chan send]:
text/template/parse.lexText(0x442007e380, 0x7f8be8)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/lex.go:248 +0x230
text/template/parse.(*lexer).run(0x442007e380)
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/lex.go:223 +0x44
created by text/template/parse.lex
        /home/docker/LibreELEC/build.LibreELEC-ROCK64.aarch64-8.2-devel/toolchain/lib/golang/src/text/template/parse/lex.go:216 +0x174
```

Here is my environment:

```
Rock64:~ # uname -a
Linux Rock64 4.4.89 #1 SMP Wed Oct 4 17:27:53 UTC 2017 aarch64 GNU/Linux
```
```

Rock64:~ # docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187d
runc version: N/A (expected: 9df8b30)
init version: 949e6fa
Kernel Version: 4.4.89
Operating System: LibreELEC (community): devel-20171004193222-r26173-gd404dbb
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 3.837 GiB
Name: Rock64
ID: 7WWJ:V4NK:J2NN:OKVB:63HR:QZUV:NCRP:75NZ:EZYS:EHRO:XCYB:MWIM
Docker Root Dir: /storage/.kodi/userdata/addon_data/service.system.docker/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Hardware platform is [Rock64](https://www.pine64.org/?page_id=7147)

**Comment by tianon** [comment]
I can't seem to reproduce: :disappointed: 
```console
$ uname -a
Linux r1-a10 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 15:00:28 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

$ docker run -it --rm arm64v8/rabbitmq:3

              RabbitMQ 3.6.14. Copyright (C) 2007-2017 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...

=INFO REPORT==== 14-Nov-2017::21:12:54 ===
Starting RabbitMQ 3.6.14 on Erlang 19.2.1
Copyright (C) 2007-2017 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 14-Nov-2017::21:12:54 ===
node           : rabbit@267f3909237f
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : bF9gyuqPuzX2mPqjw5NzSA==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@267f3909237f

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
Memory high watermark set to 6418 MiB (6730271948 bytes) of 16046 MiB (16825679872 bytes) total

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
Enabling free disk space monitoring

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
Disk free limit set to 50MB

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@267f3909237f is empty. Initialising from scratch...

=INFO REPORT==== 14-Nov-2017::21:12:57 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Starting rabbit_node_monitor

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Adding vhost '/'

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Creating user 'guest'

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Setting user tags for user 'guest' to [administrator]

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 14-Nov-2017::21:12:58 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 14-Nov-2017::21:12:58 ===
started TCP Listener on [::]:5672
 completed with 0 plugins.

=INFO REPORT==== 14-Nov-2017::21:12:59 ===
Server startup complete; 0 plugins started.
```

**Comment by zarusz** [comment]
@tianon thanks for confirming it works for you.
In the end I rebooted my OS and recreated the image and the container started to work (magic!).
Closing issue.
