### ISSUE TITLE
Impossible to use SSL connections

### ISSUE THREAD

**Issue by galzetta** [docker-library/rabbitmq#476]
I'm trying to run a RabbitMQ Pod with SSL on a Kubernetes cluster.

I define the env variables:

```
- name: RABBITMQ_MANAGEMENT_SSL_CACERTFILE
  value: /certs/rabbit_cert.pem
- name: RABBITMQ_MANAGEMENT_SSL_CERTFILE
  value: /certs/rabbit_cert.pem
- name: RABBITMQ_MANAGEMENT_SSL_KEYFILE
  value: /certs/rabbit_cert.key
- name: RABBITMQ_SSL_CACERTFILE
  value: /certs/rabbit_cert.pem
- name: RABBITMQ_SSL_CERTFILE
  value: /certs/rabbit_cert.pem
- name: RABBITMQ_SSL_KEYFILE
  value: /certs/rabbit_cert.key
```
 (obviously a test setup)

In the logs I see that the listeners for SSL **do** start:

```
2021-03-26 15:47:25.475 [info] <0.44.0> Application cowlib started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.476 [info] <0.44.0> Application cowboy started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.477 [info] <0.44.0> Application rabbitmq_web_dispatch started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.478 [info] <0.44.0> Application amqp_client started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.589 [info] <0.812.0> Management plugin: HTTPS listener started on port 15671
2021-03-26 15:47:25.590 [info] <0.920.0> Statistics database started.
2021-03-26 15:47:25.590 [info] <0.919.0> Starting worker pool 'management_worker_pool' with 3 processes in it
2021-03-26 15:47:25.593 [info] <0.44.0> Application rabbitmq_management started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.675 [info] <0.44.0> Application prometheus started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.691 [info] <0.933.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
2021-03-26 15:47:25.693 [info] <0.44.0> Application rabbitmq_prometheus started on node 'rabbit@rabbitmq-a'
2021-03-26 15:47:25.692 [info] <0.753.0> Ready to start client connection listeners
2021-03-26 15:47:25.700 [info] <0.1052.0> started TCP listener on [::]:5672
2021-03-26 15:47:25.705 [info] <0.1069.0> started TLS (SSL) listener on [::]:5671
2021-03-26 15:47:28.703 [info] <0.753.0> Server startup complete; 4 plugins started.
```

Unfortunately if I do `rabbitmq-diagnostics status` it gives an error:

```
Error: unable to perform an operation on node 'rabbit@rabbitmq-a'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@rabbitmq-a
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: ['rabbit@rabbitmq-a']

rabbit@rabbitmq-a:
  * connected to epmd (port 4369) on rabbitmq-a
  * epmd reports: node 'rabbit' not running at all
                  other nodes on rabbitmq-a: ['rabbitmqcli-415-rabbit']
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-481-rabbit@rabbitmq-a'
 * effective user's home directory: /var/lib/rabbitmq
 * Erlang cookie hash:<some hash>
```

Starting the container without SSL works fine and `rabbitmq-diagnostics status` returns the correct output without errors.

Note that this is a single container, so there is no cluster, no possible problem with multiple nodes being out of sync etc.

Running `netstat -tulpn` inside the container I see that the listeners are active (although I don't understand why some ports are bound to localhost and other to `0.0.0.0`...):

```
# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15692           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15671           0.0.0.0:*               LISTEN      -
tcp        0      0 :::5671                 :::*                    LISTEN      -
tcp        0      0 :::5672                 :::*                    LISTEN      -
tcp        0      0 :::4369                 :::*                    LISTEN      -
```

If I try to `telnet 127.0.0.1 5671` it connects (with `5672` too).

Here are the logs:
[logs-from-rabbitmq-a-in-rabbitmq-a.txt](https://github.com/docker-library/rabbitmq/files/6213070/logs-from-rabbitmq-a-in-rabbitmq-a.txt)

Is this a bug in the docker image or a problem on how SSL is configured. The docker Hub page simply says to use the env variables without any information and I tried to follow a couple of online guides to generate the correct certificates and IMHO if the listeners start that should mean Rabbit liked the certificates, right?

---

I forgot to mention, my application using Micronaut fails to connect with this error:

```
Caused by: io.micronaut.messaging.exceptions.MessageListenerException: Failed to retrieve a channel pool named [default] to register a listener
	at io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:124)
	at io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:67)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:95)
	... 15 common frames omitted
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error creating connection to RabbitMQ
	at io.micronaut.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:62)
	at io.micronaut.rabbitmq.connect.$RabbitConnectionFactory$Connection0Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:153)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:752)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:142)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:729)
	at io.micronaut.rabbitmq.intercept.RabbitMQConsumerAdvice.process(RabbitMQConsumerAdvice.java:122)
	... 17 common frames omitted
Caused by: javax.net.ssl.SSLException: readHandshakeRecord
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
	at java.base/java.io.DataOutputStream.flush(Unknown Source)
	at com.rabbitmq.client.impl.SocketFrameHandler.sendHeader(SocketFrameHandler.java:160)
	at com.rabbitmq.client.impl.SocketFrameHandler.sendHeader(SocketFrameHandler.java:170)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:314)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1130)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1087)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1045)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1238)
	at io.micronaut.rabbitmq.connect.RabbitConnectionFactory.connection(RabbitConnectionFactory.java:59)
	... 34 common frames omitted
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
		at java.base/java.net.SocketOutputStream.write(Unknown Source)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
		... 50 common frames omitted
Caused by: java.net.SocketException: Connection reset by peer (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.base/java.net.SocketOutputStream.write(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(Unknown Source)
	at java.base/sun.security.ssl.HandshakeOutStream.flush(Unknown Source)
	at java.base/sun.security.ssl.ECDHClientKeyExchange$ECDHEClientKeyExchangeProducer.produce(Unknown Source)
	at java.base/sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.produce(Unknown Source)
	at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	... 51 common frames omitted
```

So it's not an out-right connection refused.

**Comment by wglambert** [comment]
Half your environment variables are for the management variant and half are for the non-management

https://github.com/docker-library/docs/tree/master/rabbitmq#environment-variables
>For SSL configuration without the management plugin:
. . .

>For SSL configuration using the management plugin:
. . .

Following the example at https://www.rabbitmq.com/ssl.html#automated-certificate-generation-transcript I was able to get ssl working https://github.com/docker-library/rabbitmq/issues/376#issuecomment-541807243
See also https://github.com/docker-library/rabbitmq/discussions/470
